#!/bin/sh



export PATH=$PATH:/usr/sbin:/sbin

mount -t proc proc /proc
mount -t sysfs none /sys
mount -t tmpfs none /tmp
mount -t tmpfs none /var/run

echo "/sbin/mdev" > /proc/sys/kernel/hotplug
mdev -s

insmod /lib/modules/`uname -r`/kernel/drivers/omapdrm_pvr.ko

for mo in omap_rpmsg_resmgr rpmsg_resmgr_common omap_remoteproc omaprpc rpmsg_omx omapdce ehci-hcd
do
    modprobe $mo
done

pvrsrvinit

alsactl restore -f /etc/asound.state

hostname -F /etc/hostname
mkdir /dev/pts && mount devpts /dev/pts -t devpts -o mode=620
dropbear

(
    echo "starting network"
    modprobe wl12xx
    modprobe wlcore_sdio
    wpa_supplicant -iwlan0 -c /etc/wpa_supplicant.conf -B
    udhcpc -i wlan0
) &

